### ISSUE TITLE
View in visual basic mvc5 project

### ISSUE THREAD

**Issue by shhfrlsk06** [kpi-ua/X.PagedList#39]
Hi, I try to used X.PagedList on VB MVC 5 project but does not successful.
The error shown are.
_Error BC30519	Overload resolution failed because no accessible 'PagedListPager' can be called without a narrowing conversion:
    Extension method 'Public Function PagedListPager(list As IPagedList, generatePageUrl As Func(Of Integer, String)) As MvcHtmlString' defined in 'HtmlHelper': Argument matching parameter 'list' narrows from 'IEnumerable(Of IdentityRole)' to 'IPagedList'.
    Extension method 'Public Function PagedListPager(list As IPagedList, generatePageUrl As Func(Of Integer, String)) As MvcHtmlString' defined in 'HtmlHelper': Argument matching parameter 'list' narrows from 'IEnumerable(Of IdentityRole)' to 'IPagedList'._

can anyone give me idea/sample on how to properly do it. already try to search on google but did not find helpful answer.
Thanks in advance..

view.vbhtml
![image](https://cloud.githubusercontent.com/assets/15355561/15844017/51311632-2c99-11e6-8fbc-885120e89f8a.png)

controller.vb
![image](https://cloud.githubusercontent.com/assets/15355561/15844033/6ff655e6-2c99-11e6-91b6-d651849b6613.png)

**Comment by ernado-x** [comment]
Could you please make repo with  example code to allow reproduce this problem?

**Comment by richin13** [comment]
Hi @ernado-x, can this package be used in VB at all? I am not being able to use the HTML Helper PagedListPager (The error message says: "PagedListPager is not a member of HtmlHelper(Of IPagedList)" while using these imports:

```
@Imports X.PagedList.Mvc
@Imports X.PagedList
@ModelType IPagedList(Of Admissions) <-- Error here that says: Type IPagedList is not defined
```

Since I am a bit new to VB and I can only see C# code in the repo, I was wondering if the package can be used in VB at all or if this package is C#-only? Thanks
